### ISSUE TITLE
Want to change editor ? 

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/apcal#36]
Hi, 
didnt find where to change editor.
This module used tinyEditor...
I prefered dhtmltextarea

ooops : In Editing/creating category (/modules/apcal/admin/categories.php)

**Comment by ggoffy** [comment]
Hi alain01

the editor is hardcoded in admin/categories.php
```
// Description
    $tarea_tray = new XoopsFormElementTray(_AM_APCAL_CAT_TH_DESC, '<br>');
    if (class_exists('XoopsFormEditor')) {
        $configs = array(
            'name'   => 'cat_desc',
            'value'  => htmlspecialchars($cat->cat_desc, ENT_QUOTES),
            'rows'   => 15,
            'cols'   => 60,
            'width'  => '100%',
            'height' => '400px',
            'editor' => 'tinymce'
        );
        $tarea_tray->addElement(new XoopsFormEditor('', 'cat_desc', $configs, false, $onfailure = 'textarea'));
    } else {
        $tarea_tray->addElement(new XoopsFormDhtmlTextArea('', 'cat_desc', htmlspecialchars($cat->cat_desc, ENT_QUOTES), 15, 60));
    }
    $form->addElement($tarea_tray);
```
so it should be tinymce or dhtmltextarea, not tinyEditor.

**Comment by alain01** [comment]
Yes, it's TinyMCE, 
i dislike,
in preferences, cant change to dhtmltextarea
Did i miss something ?

**Comment by alain01** [comment]
Editor for all modules: dhtmltextarea

**Comment by ggoffy** [comment]
yes, apcal is ignoring general settings. and apcal is a horrible module to maintain, because it partially hardcoded, partially template based, a lot of includes, a lot of functions duplicating xoops functions and so on. Therefore I will not touch it for the moment (not enough time), especially on user side (creating an event, where also textarea is used).

In your case: if you want to have dhtmleditor only for handling categories then replace code block from above by
`$tarea_tray->addElement(new XoopsFormDhtmlTextArea('', 'cat_desc', htmlspecialchars($cat->cat_desc, ENT_QUOTES), 15, 60));`

**Comment by alain01** [comment]
Thanks for the answer and i'm very sorry to take youu time for that.
i've just writte some remarks/issues cause i've just tested this module.
I cant use this, lot of functionnalities but not really friendly.
Ok, i should ask to Greg (or you ;-) ) to create a nice agenda module with full xmf code and bt4 design.

**Comment by mambax7** [comment]
I'm wondering why aren't we focusing on improving extCal that has more current architecture, instead of spending time on Apcal that is older? 
Could we move the best features from Apcal to extCal?  Just curious....

**Comment by alain01** [comment]
ok, i will test extcal.
Go to the extCal github repository for issues ;-)

**Comment by ggoffy** [comment]
hi Michael
of course you are right, it is not worth to update apcal to current standards. I am only trying to "keep apcal alive", because I need the online registration for two websites.

and calendar module is on my agenda already :)
